Repository acm-ucr/ewb-website, pull requests merged in 2023-11, with the labels that each got.

#55 added Picture
  src/components/Picture.jsx
Labels: ready for review

#32 kevin/event
  src/app/page.js
  src/components/home/Event.jsx
  src/components/home/Events.jsx
Labels: ready for review

#29 Add Subtitle
  src/app/page.js
  src/components/Subtitle.jsx
Labels: changes requested

#57 join us section added
  src/app/page.js
  src/components/home/Join.jsx
Labels: ready for review

#53 kevin/footer
  src/components/Footer.jsx
Labels: ready for review

#58 stanley/costaRicaPage
  src/app/projects/costa-rica/page.js
  src/components/Subtitle.jsx
  src/components/projects/CostaRica.jsx
Labels: ready for review

#51 Added Project Header
  src/components/projects/Header.jsx
Labels: changes requested

#59 Created Air Quality page
  src/app/projects/air-quality-system/page.js
  src/components/projects/ AirQuality.jsx
Labels: changes requested, projects page

#63 Added Tanazania
  src/components/projects/Tanzania.jsx
Labels: ready for review

#67 Created Landing Page
  src/components/home/Landing.jsx
Labels: home page, ready for review

#72 Kevin/project section
  src/components/home/Project.jsx
  src/components/home/Projects.jsx
Labels: ready for review

#65 Fuyuki/mobile footer
  src/components/Footer.jsx
Labels: ready for review

#66 Fuyuki/Mobile-Responsiveness-Event
  .github/workflows/nextjs.yml
  .github/workflows/pull-request.yaml
  package-lock.json
  package.json
  src/components/home/Event.jsx
Labels: changes requested

#77 Added board
  src/app/board/page.js
  src/components/Title.jsx
  src/components/board/Board.jsx
  src/data/icons.js
  src/data/mockBoard.js
Labels: board page

#86 stanley/whyjoin
  src/components/Title.jsx
  src/components/home/Focus.jsx
  src/components/home/WhyJoin.jsx
Labels: ready for review

#88 Dylan/water quality and filtration project
  src/components/projects/WaterQuality.jsx
Labels: changes requested

#84 Fuyuki/Mobile-Responsive-Costa-Rica
  src/components/projects/CostaRica.jsx
Labels: ready for review

#98 stanley/robotics
  src/app/projects/robotics/page.js
  src/components/projects/Robotics.jsx
Labels: ready for review

#99 stanley / mobile responsiveness for focus section
  src/components/home/Focus.jsx
Labels: ready for review

#107 added board mobile responsiveness
  src/app/board/page.js
Labels: ready for review, mobile responsive

#102 stanley/whyjoin
  src/components/home/Focus.jsx
  src/components/home/WhyJoin.jsx
Labels: ready for review

#106 Landing page now responsive on most mobile phones
  src/components/home/Landing.jsx
Labels: ready for review, mobile responsive

#104 kevin/tanzaniaMobile
  src/components/projects/Tanzania.jsx
Labels: ready for review

#105 Fuyuki/About
  src/components/home/About.jsx
Labels: ready for review

#87 Created About Page
  public/images/AboutPic1.webp
  public/images/AboutPic2.webp
  src/app/about/page.js
  src/components/Subtitle.jsx
Labels: about page, changes requested

#120 Removed board margin
  src/components/board/Board.jsx
Labels: board page, ready for review

#123 kevin/exclamationMark
  src/components/home/WhyJoin.jsx
Labels: ready for review

#126 stanley/video
  src/components/projects/WaterQuality.jsx
Labels: ready for review

#125 kevin/linkSpace
  src/app/projects/tanzania/page.js
  src/components/projects/ AirQuality.jsx
  src/components/projects/CostaRica.jsx
  src/components/projects/Robotics.jsx
  src/components/projects/WaterQuality.jsx
Labels: ready for review

#128 added WaterQualityHeader
  src/app/projects/water-quality-and-filtration/page.js
Labels: ready for review, projects page

#124 kevin/circle
  src/app/about/page.js
  src/app/board/page.js
Labels: ready for review
